version: "3"
services:
        nginx:
                container_name: nginx
                image:  nginx:latest
                restart: always
                ports:
                        - 80:80
                volumes:
                        - $HOME/nginx/nginx.conf:/etc/nginx/nginx.conf
                        - $HOME/html:/root/html
